app = "ai-hiring-ml"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true

[[services]]
  internal_port = 8000
  processes = ["app"]