apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-hiring-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.ai-hiring.com
    secretName: ai-hiring-tls
  rules:
  - host: api.ai-hiring.com
    http:
      paths:
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: main-api-service
            port:
              number: 80
      - path: /ml/(.*)
        pathType: Prefix
        backend:
          service:
            name: ml-service
            port:
              number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-hiring-staging-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - staging-api.ai-hiring.com
    secretName: ai-hiring-staging-tls
  rules:
  - host: staging-api.ai-hiring.com
    http:
      paths:
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: main-api-service
            port:
              number: 80
      - path: /ml/(.*)
        pathType: Prefix
        backend:
          service:
            name: ml-service
            port:
              number: 8000