apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-api
  namespace: ai-hiring
  labels:
    app: main-api
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: main-api
  template:
    metadata:
      labels:
        app: main-api
        version: v1
    spec:
      serviceAccountName: ai-hiring-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: main-api
        image: manziosee/ai-hiring-backend:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: ML_SERVICE_HOST
          value: "ml-service"
        - name: ML_SERVICE_PORT
          value: "8000"
        - name: EMAIL_SERVICE_HOST
          value: "email-service"
        - name: EMAIL_SERVICE_PORT
          value: "3002"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: NODE_ENV
          value: "production"
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app-url
        - name: THROTTLE_TTL
          value: "60000"
        - name: THROTTLE_LIMIT
          value: "10"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: openai-api-key
        - name: HUGGINGFACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: huggingface-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: temp
          mountPath: /tmp
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: temp
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: main-api
  namespace: ai-hiring
  labels:
    app: main-api
spec:
  type: ClusterIP
  selector:
    app: main-api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ai-hiring
data:
  app-url: "https://api.ai-hiring.example.com"
  environment: "production"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: ai-hiring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd