apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ai-hiring
type: Opaque
data:
  password: cGFzc3dvcmQ= # base64 encoded "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ai-hiring
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvYWktaGlyaW5nLWRi # base64 encoded connection string
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg== # base64 encoded secret
  email-user: eW91ci1lbWFpbEBnbWFpbC5jb20= # base64 encoded email
  email-password: eW91ci1hcHAtcGFzc3dvcmQ= # base64 encoded app password