# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.9'

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install backend dependencies
      run: cd backend && npm install --legacy-peer-deps

    - name: Generate Prisma client
      run: cd backend && npm run prisma:generate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Run database migrations
      run: cd backend && npm run prisma:migrate
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db

    - name: Run backend tests
      run: cd backend && npm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        JWT_SECRET: test-secret
        REDIS_URL: redis://localhost:6379

    - name: Run e2e tests
      run: cd backend && npm run test:e2e
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        JWT_SECRET: test-secret
        REDIS_URL: redis://localhost:6379

    - name: Generate test coverage
      run: cd backend && npm run test:cov
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        JWT_SECRET: test-secret

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install backend dependencies
      run: cd backend && npm install --legacy-peer-deps

    - name: Run backend linting
      run: cd backend && npm run lint

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install backend dependencies
      run: cd backend && npm install --legacy-peer-deps

    - name: Run security audit
      run: cd backend && npm audit --audit-level moderate

    - name: Run Snyk security scan
      if: ${{ vars.SNYK_TOKEN != '' }}
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ vars.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [test, lint, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Install backend dependencies
      run: cd backend && npm install --legacy-peer-deps

    - name: Build backend
      run: cd backend && npm run build

    - name: Build Docker image
      run: |
        docker build -t ai-hiring-backend:${{ github.sha }} .
        docker build -t ai-hiring-backend:latest .

    - name: Save Docker image
      run: docker save ai-hiring-backend:latest | gzip > ai-hiring-backend.tar.gz

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: ai-hiring-backend.tar.gz

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker image
      run: docker load < ai-hiring-backend.tar.gz

    - name: Setup Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io Staging
      if: ${{ vars.FLY_API_TOKEN != '' }}
      run: flyctl deploy --remote-only --app ai-hiring-api-staging
      env:
        FLY_API_TOKEN: ${{ vars.FLY_API_TOKEN }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      if: ${{ vars.KUBE_CONFIG_STAGING != '' }}
      run: |
        mkdir -p ~/.kube
        echo "${{ vars.KUBE_CONFIG_STAGING }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes Staging
      if: ${{ vars.KUBE_CONFIG_STAGING != '' }}
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/main-api.yaml -n ai-hiring-staging
        kubectl apply -f kubernetes/ml-service.yaml -n ai-hiring-staging
        kubectl apply -f kubernetes/redis.yaml -n ai-hiring-staging
        kubectl apply -f kubernetes/ingress.yaml -n ai-hiring-staging

    - name: Run smoke tests
      run: |
        echo "Running smoke tests on staging..."
        npm run test:smoke -- --baseUrl=https://ai-hiring-api-staging.fly.dev

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: docker-image

    - name: Load Docker image
      run: docker load < ai-hiring-backend.tar.gz

    - name: Setup Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io Production
      if: ${{ vars.FLY_API_TOKEN != '' }}
      run: flyctl deploy --remote-only --app ai-hiring-api
      env:
        FLY_API_TOKEN: ${{ vars.FLY_API_TOKEN }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      if: ${{ vars.KUBE_CONFIG != '' }}
      run: |
        mkdir -p ~/.kube
        echo "${{ vars.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Deploy to Kubernetes Production
      if: ${{ vars.KUBE_CONFIG != '' }}
      run: |
        kubectl apply -f kubernetes/namespace.yaml
        kubectl apply -f kubernetes/main-api.yaml -n ai-hiring
        kubectl apply -f kubernetes/ml-service.yaml -n ai-hiring
        kubectl apply -f kubernetes/redis.yaml -n ai-hiring
        kubectl apply -f kubernetes/ingress.yaml -n ai-hiring

    - name: Run production health check
      run: |
        echo "Running production health check..."
        curl -f https://ai-hiring-api.fly.dev/health || exit 1

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always()
    
    steps:
    - name: Notify Slack
      if: ${{ vars.SLACK_WEBHOOK_URL != '' }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
      env:
        SLACK_WEBHOOK_URL: ${{ vars.SLACK_WEBHOOK_URL }}
